dist: bionic
git:
  depth: 3
language: python
python:
  - "2.7"
# command to install dependencies
before_install: 
  - sudo apt-get update -y
  - sudo apt-get update
  - sudo apt install cmake g++ git make python3 zlib1g-dev libgmp3-dev
install: 
  - chmod +x *.sh
  - ./prepare-fd.sh
  - chmod +x *.py
script: 
  - mkdir outputs
  - mkdit data-charts
  - mkdir data-latex
  - ./test_units.py
  - ./test_instance.py -r delta -e experiments/small-sokoban/50/sokoban_p01_hyp-1_50_1.tar.bz2
  - ./test_domain.py experiments small-sokoban "delta delta-f2 delta-cl delta-cp delta-cs delta-cd delta-f1" -S soplex
branches:
  only:
    - master