dist: bionic
git:
  depth: 3
language: python
python:
  - "2.7"
# command to install dependencies
before_install: 
  - sudo apt-get update -y
  - sudo apt-get update
  - sudo apt install cmake g++ mercurial make python3 zlib1g-dev libgmp3-dev
install: 
  - chmod +x *.sh
  - ./prepare-fd.sh
script: 
  - ./test_units.py
  - ./test_instance.py -r dc -e experiments/small-sokoban/50/sokoban_p01_hyp-1_50_1.tar.bz2
  - ./test_domain.py experiments small-sokoban v hu c dc dcu s ds dsu w wu dc-f1 dcu-f1 dc-f2 dcu-f2
branches:
  only:
    - master