dist: bionic
git:
  depth: 3
language: python
python:
  - "2.7"
# command to install dependencies
before_install: 
  - sudo apt-get update -y
  - sudo apt-get update
  - sudo apt install cmake g++ mercurial make python3 zlib1g-dev libgmp3-dev
install: 
  - chmod +x *.sh
  - ./prepare-fd.sh
script: 
  - python test_lp_recognizer.py
branches:
  only:
    - master
    - refactor